export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <p>About Layout</p>
        </div>
        {children}
      </body>
    </html>
  );
}
